version: '3.5'
services:

    database:
        image: db
        build: ./.db
        ports:
            - "3306:3306"
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: restaurants_geolocation_api
        volumes:
            - db-volume:/var/lib/mysql
volumes:
    db-volume: